<?php

namespace DemoBundle\Repository;

/**
 * TaskTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
