demo:
    resource: "@DemoBundle/Controller/"
    type:     annotation
    prefix:   /

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
